"""
V9.0 Autonomous Investment Committee Engine

Purpose:
Simulate institutional investment committee
decision making.

Committee Members:
- CIO
- Risk Officer
- Quant Analyst
- Portfolio Manager

Output:
Final investment approval decision
"""


from datetime import datetime



def evaluate_cio_view(
    alpha_score
):
    """
    CIO opportunity assessment
    """

    if alpha_score >= 85:

        return "APPROVE"


    elif alpha_score >= 70:

        return "REVIEW"


    else:

        return "REJECT"





def evaluate_risk_officer(
    risk_level,
    position_weight
):
    """
    Risk committee assessment
    """


    if risk_level == "HIGH":

        return "REJECT"


    if position_weight > 10:

        return "REDUCE_SIZE"


    return "APPROVE"





def evaluate_quant_model(
    model_score
):
    """
    Quant validation
    """


    if model_score >= 80:

        return "APPROVE"


    elif model_score >= 60:

        return "REVIEW"


    else:

        return "REJECT"





def generate_committee_decision(
    ticker,
    alpha_score,
    risk_level,
    position_weight,
    quant_score
):
    """
    Final Investment Committee decision
    """


    cio_vote = evaluate_cio_view(
        alpha_score
    )


    risk_vote = evaluate_risk_officer(
        risk_level,
        position_weight
    )


    quant_vote = evaluate_quant_model(
        quant_score
    )



    votes = [

        cio_vote,

        risk_vote,

        quant_vote

    ]



    if "REJECT" in votes:

        decision = "REJECTED"



    elif "REDUCE_SIZE" in votes:

        decision = "APPROVED_REDUCED"



    elif votes.count(
        "APPROVE"
    ) >= 2:

        decision = "APPROVED"



    else:

        decision = "UNDER_REVIEW"




    return {


        "engine":

        "V9.0 Autonomous Investment Committee",


        "timestamp":

        datetime.utcnow().isoformat(),


        "ticker":

        ticker,


        "committee_decision":

        decision,


        "votes":

        {


            "cio":

            cio_vote,


            "risk_officer":

            risk_vote,


            "quant":

            quant_vote

        },


        "allocation":

        position_weight,


        "reason":

        "Decision generated by multi-agent investment committee."

    }





def run_investment_committee(
    opportunities
):
    """
    Reviews multiple opportunities
    """


    decisions = []



    for opportunity in opportunities:


        decision = generate_committee_decision(

            opportunity.get(
                "ticker"
            ),

            opportunity.get(
                "alpha_score",
                0
            ),

            opportunity.get(
                "risk_level",
                "MEDIUM"
            ),

            opportunity.get(
                "position_weight",
                5
            ),

            opportunity.get(
                "quant_score",
                0
            )

        )


        decisions.append(
            decision
        )



    return decisions
